#!/usr/bin/expect

source "/usr/local/2nd_tools/lib/env.exp"
source "$base_dir/lib/func.exp"

log_user 0
mgtcb_login "vsys-db"
send -- "/usr/local/mysql/bin/mysql -usopuser -p'mtm!0256' sop\n"
expect -re $prompt
stdout "select sw.software_id,sl.image_id,sw.os_category from software sw,software_link sl where sw.software_id = sl.software_id and sw.os_category is not NULL;"
send -- "quit\n"
expect -re $prompt
send -- "exit\n"
expect eof

