#!/usr/bin/expect

source "/usr/local/2nd_tools/lib/env.exp"
source "$base_dir/lib/func.exp"

set server "yumntpdns-dmz"

log_user 0
mgtcb_login $server
while { [gets stdin line] >= 0 } {
	send_user -- "$line START\n"
	send -- "nslookup -type=ptr $line\n"
	expect -re ".*?\n"
	while {1} {
		expect -re ".*\n" {
			send_user -- "$expect_out(buffer)"
		} "# " {
			break
		}
	}
}
send -- "exit\n"
expect eof
