#!/usr/bin/expect

source "/usr/local/2nd_tools/lib/env.exp"
source "$base_dir/lib/func.exp"

log_user 0
island_login "admin-pr"
while {[gets stdin line] >= 0} {
	set user [lindex [split $line ","] 0]
	set pass [lindex [split $line ","] 1]
	send -- "/opt/cockpit/bin/ldappasswd\n"
	expect "E-Mail Address or User ID"
	send -- "$user\n"
	expect "Password:"
	send -- "$pass\n"
	expect -re $prompt
}
send -- "exit\n"
expect eof
exit
