#!/usr/bin/expect

source "/usr/local/2nd_tools/lib/env.exp"
source "$base_dir/lib/func.exp"

log_user 0
mgtcb_login "vsys-db"
send -- "/usr/local/mysql/bin/mysql -u sopuser -p'mtm!0256' sop\n"
expect -re $prompt
stdout "select org_id,server_type,count(*) from `server#instance` where status not in('UNDEPLOY','UNDEPLOYING','UNALLOCATED','ERROR') group by org_id,server_type;"
send -- "quit\n"
expect -re $prompt
send -- "exit\n"
expect eof
