#!/usr/bin/expect

set server [lindex $argv 0]
set timeout 5
log_user 0
spawn ssh -l root $server
expect "password" {
	send -- "sr@01011\n"
} "yes/no" {
	send -- "yes\n"
	expect "password"
	send -- "sr@01011\n"
} timeout {
	puts "TIMEOUT"
	exit
} eof {
	puts "FAILED"
	exit
}

#set timeout -1
expect "# "
send -- "xm list\n"
expect -re ".*?\n"
while {1} {
	expect -re ".*\n" {
		send_user -- "$expect_out(buffer)"
	} "# " {
		break
	}
}
send -- "exit\n"
expect eof
