#!/usr/bin/expect

source	"/usr/local/2nd_tools/lib/env.exp"
source	"$base_dir/lib/func.exp"

#log_user 0
set island [lindex $argv 0]
set	timeout 5

trap	{} {SIGHUP}


spawn	/bin/bash
expect -re $prompt
send -- "curl -k -X GET  -H 'Content-Type: application/xml' -H 'Authorization: Basic cm9vdDpzb3B4ZW4=' 'https://$island-cbrm:23461/physical_servers' \n" 
expect -re $prompt
send -- "exit\n"
expect eof
