#!/usr/bin/expect

### VERSION 1.0 ###

source "/usr/local/2nd_tools/lib/env.exp"
source "$base_dir/lib/func.exp"

set dom0 [lindex $argv 0]
set island [lindex $argv 1]

log_user 0
set ret 0
island_login $island
send -- "/opt/FJSVrcvmr/bin/rcxadm server list|grep $dom0\n"
expect -re ".*?\n"
while {1} {
	expect -re ".*\n" {
		set ret 1
	} -re $prompt {
		break
	}
}

send_user -- $ret

send -- "exit\n"
expect eof
log_user 1
